# DATA PATHS

DATA_DIR = "data"
DATA_DIR_RAW = DATA_DIR + "/raw"
DATA_DIR_PROC = DATA_DIR + "/processed"

DATA_TRAIN_RAW = DATA_DIR_RAW + "/train.json"
DATA_TRAIN_PROC = DATA_DIR_PROC + "/train.csv"

DATA_EVAL_RAW = DATA_DIR_RAW + "/dev.json"
DATA_EVAL_PROC = DATA_DIR_PROC + "/eval.csv"

DATA_TEST_RAW = DATA_DIR_RAW + "/test.json"
DATA_TEST_PROC = DATA_DIR_PROC + "/test.csv"

DATA_DOCUMENTS = DATA_DIR_PROC + "/documents.csv"
DATA_DOCUMENTS_AUG = DATA_DIR_PROC + "/documents_aug.csv"


# MODEL PATHS

MODELS_DIR = "models"


# CONFIG

SEPARATOR = "-"
KEYWORDS_NGRAM_SIZE = 2  # Code is hardcoded for pairs
KEYWORDS_DIVERSITY = 0.5
KEYWORDS_TOP_N = 2
USE_COMPANY_YEAR_IN_DOCID = True
DOCID_SIZE = KEYWORDS_NGRAM_SIZE * KEYWORDS_TOP_N + (2 if USE_COMPANY_YEAR_IN_DOCID else 0)
